import type * as Monaco from 'monaco-editor/esm/vs/editor/editor.api'

type MonacoApi = typeof Monaco

const darkPlusRules: Monaco.editor.ITokenThemeRule[] = [
  { token: '', foreground: 'D4D4D4', background: '111418' },
  { token: 'invalid', foreground: 'F44747' },
  { token: 'emphasis', fontStyle: 'italic' },
  { token: 'strong', fontStyle: 'bold' },
  { token: 'comment', foreground: '6A9955' },
  { token: 'comment.doc', foreground: '6A9955' },
  { token: 'comment.doc.tag', foreground: 'DCDCAA', fontStyle: 'bold' },
  { token: 'comment.content', foreground: '6A9955' },
  { token: 'keyword', foreground: '569CD6' },
  { token: 'keyword.control', foreground: 'C586C0' },
  { token: 'keyword.declaration', foreground: '569CD6', fontStyle: 'bold' },
  { token: 'keyword.modifier', foreground: '569CD6' },
  { token: 'keyword.operator', foreground: 'D4D4D4' },
  { token: 'operator', foreground: 'D4D4D4' },
  { token: 'delimiter', foreground: 'D4D4D4' },
  { token: 'delimiter.html', foreground: '808080' },
  { token: 'delimiter.xml', foreground: '808080' },
  { token: 'delimiter.cdata.xml', foreground: '808080' },
  { token: 'delimiter.curly', foreground: 'FFD700' },
  { token: 'delimiter.square', foreground: 'DA70D6' },
  { token: 'delimiter.angle', foreground: '808080' },
  { token: 'delimiter.bracket', foreground: 'D4D4D4' },
  { token: 'delimiter.parenthesis', foreground: 'D4D4D4' },
  { token: 'identifier', foreground: 'D4D4D4' },
  { token: 'string', foreground: 'CE9178' },
  { token: 'string.block', foreground: 'CE9178' },
  { token: 'string.char', foreground: 'CE9178' },
  { token: 'string.escape', foreground: 'D7BA7D' },
  { token: 'string.escape.invalid', foreground: 'F44747' },
  { token: 'string.escape.xml', foreground: 'D7BA7D' },
  { token: 'string.key', foreground: '9CDCFE' },
  { token: 'string.key.json', foreground: '9CDCFE' },
  { token: 'string.value.json', foreground: 'CE9178' },
  { token: 'number', foreground: 'B5CEA8' },
  { token: 'number.float', foreground: 'B5CEA8' },
  { token: 'number.hex', foreground: 'B5CEA8' },
  { token: 'regexp', foreground: 'D16969' },
  { token: 'type', foreground: '4EC9B0' },
  { token: 'type.primitive', foreground: '4EC9B0', fontStyle: 'bold' },
  { token: 'type.identifier', foreground: '4EC9B0' },
  { token: 'class', foreground: '4EC9B0' },
  { token: 'interface', foreground: '4EC9B0' },
  { token: 'enum', foreground: '4EC9B0' },
  { token: 'namespace', foreground: '4EC9B0' },
  { token: 'function', foreground: 'DCDCAA' },
  { token: 'function.call', foreground: 'DCDCAA' },
  { token: 'member', foreground: 'DCDCAA' },
  { token: 'macro', foreground: 'DCDCAA' },
  { token: 'variable', foreground: '9CDCFE' },
  { token: 'variable.predefined', foreground: '569CD6' },
  { token: 'parameter', foreground: '9CDCFE' },
  { token: 'property', foreground: '9CDCFE' },
  { token: 'property.name', foreground: '9CDCFE' },
  { token: 'property.value', foreground: 'CE9178' },
  { token: 'enum-member', foreground: '4FC1FF' },
  { token: 'constant', foreground: '4FC1FF' },
  { token: 'constant.language', foreground: '569CD6', fontStyle: 'bold' },
  { token: 'annotation', foreground: 'DCDCAA', fontStyle: 'italic' },
  { token: 'tag', foreground: '569CD6' },
  { token: 'tag.html', foreground: '569CD6' },
  { token: 'tag.xml', foreground: '569CD6' },
  { token: 'metatag', foreground: '569CD6' },
  { token: 'metatag.xml', foreground: 'C586C0' },
  { token: 'metatag.content', foreground: '9CDCFE' },
  { token: 'metatag.content.html', foreground: '9CDCFE' },
  { token: 'attribute.name', foreground: '9CDCFE' },
  { token: 'attribute.name.html', foreground: '9CDCFE' },
  { token: 'attribute.name.xml', foreground: '9CDCFE' },
  { token: 'attribute.value', foreground: 'CE9178' },
  { token: 'attribute.value.html', foreground: 'CE9178' },
  { token: 'attribute.value.xml', foreground: 'CE9178' },
  { token: 'attribute.value.number', foreground: 'B5CEA8' },
  { token: 'attribute.value.unit', foreground: 'B5CEA8' },
  { token: 'key', foreground: '9CDCFE' },
  { token: 'key.yaml', foreground: '9CDCFE' },
  { token: 'predefined', foreground: '569CD6' },
  { token: 'support.type', foreground: '4EC9B0' },
  { token: 'support.class', foreground: '4EC9B0' },
  { token: 'support.function', foreground: 'DCDCAA' },
  { token: 'support.constant', foreground: '4FC1FF' },
  { token: 'metatag.html', foreground: '808080' },
  { token: 'type.identifier.css', foreground: 'D7BA7D' },
  { token: 'attribute.name.css', foreground: '9CDCFE' },
  { token: 'attribute.value.css', foreground: 'CE9178' },
  { token: 'keyword.css', foreground: 'C586C0' },
]

const lightPlusRules: Monaco.editor.ITokenThemeRule[] = [
  { token: '', foreground: '000000', background: 'F8FAFC' },
  { token: 'invalid', foreground: 'CD3131' },
  { token: 'emphasis', fontStyle: 'italic' },
  { token: 'strong', fontStyle: 'bold' },
  { token: 'comment', foreground: '008000' },
  { token: 'comment.doc', foreground: '008000' },
  { token: 'comment.doc.tag', foreground: '795E26', fontStyle: 'bold' },
  { token: 'comment.content', foreground: '008000' },
  { token: 'keyword', foreground: '0000FF' },
  { token: 'keyword.control', foreground: 'AF00DB' },
  { token: 'keyword.declaration', foreground: '0000FF', fontStyle: 'bold' },
  { token: 'keyword.modifier', foreground: '0000FF' },
  { token: 'keyword.operator', foreground: '000000' },
  { token: 'operator', foreground: '000000' },
  { token: 'delimiter', foreground: '000000' },
  { token: 'delimiter.html', foreground: '800000' },
  { token: 'delimiter.xml', foreground: '800000' },
  { token: 'delimiter.cdata.xml', foreground: '800000' },
  { token: 'delimiter.curly', foreground: '795E26' },
  { token: 'delimiter.square', foreground: 'AF00DB' },
  { token: 'delimiter.angle', foreground: '800000' },
  { token: 'delimiter.bracket', foreground: '000000' },
  { token: 'delimiter.parenthesis', foreground: '000000' },
  { token: 'identifier', foreground: '000000' },
  { token: 'string', foreground: 'A31515' },
  { token: 'string.block', foreground: 'A31515' },
  { token: 'string.char', foreground: 'A31515' },
  { token: 'string.escape', foreground: 'EE0000' },
  { token: 'string.escape.invalid', foreground: 'CD3131' },
  { token: 'string.escape.xml', foreground: 'EE0000' },
  { token: 'string.key', foreground: '001080' },
  { token: 'string.key.json', foreground: 'A31515' },
  { token: 'string.value.json', foreground: '0451A5' },
  { token: 'number', foreground: '098658' },
  { token: 'number.float', foreground: '098658' },
  { token: 'number.hex', foreground: '098658' },
  { token: 'regexp', foreground: '811F3F' },
  { token: 'type', foreground: '267F99' },
  { token: 'type.primitive', foreground: '267F99', fontStyle: 'bold' },
  { token: 'type.identifier', foreground: '267F99' },
  { token: 'class', foreground: '267F99' },
  { token: 'interface', foreground: '267F99' },
  { token: 'enum', foreground: '267F99' },
  { token: 'namespace', foreground: '267F99' },
  { token: 'function', foreground: '795E26' },
  { token: 'function.call', foreground: '795E26' },
  { token: 'member', foreground: '795E26' },
  { token: 'macro', foreground: '795E26' },
  { token: 'variable', foreground: '001080' },
  { token: 'variable.predefined', foreground: '0000FF' },
  { token: 'parameter', foreground: '001080' },
  { token: 'property', foreground: '001080' },
  { token: 'property.name', foreground: '001080' },
  { token: 'property.value', foreground: 'A31515' },
  { token: 'enum-member', foreground: '0070C1' },
  { token: 'constant', foreground: '0070C1' },
  { token: 'constant.language', foreground: '0000FF', fontStyle: 'bold' },
  { token: 'annotation', foreground: 'B000B0', fontStyle: 'italic' },
  { token: 'tag', foreground: '800000' },
  { token: 'tag.html', foreground: '800000' },
  { token: 'tag.xml', foreground: '800000' },
  { token: 'metatag', foreground: '800000' },
  { token: 'metatag.xml', foreground: 'AF00DB' },
  { token: 'metatag.content', foreground: '001080' },
  { token: 'metatag.content.html', foreground: '001080' },
  { token: 'attribute.name', foreground: 'FF0000' },
  { token: 'attribute.name.html', foreground: 'FF0000' },
  { token: 'attribute.name.xml', foreground: 'FF0000' },
  { token: 'attribute.value', foreground: '0000FF' },
  { token: 'attribute.value.html', foreground: '0000FF' },
  { token: 'attribute.value.xml', foreground: '0000FF' },
  { token: 'attribute.value.number', foreground: '098658' },
  { token: 'attribute.value.unit', foreground: '098658' },
  { token: 'key', foreground: '001080' },
  { token: 'key.yaml', foreground: '001080' },
  { token: 'predefined', foreground: '0000FF' },
  { token: 'support.type', foreground: '267F99' },
  { token: 'support.class', foreground: '267F99' },
  { token: 'support.function', foreground: '795E26' },
  { token: 'support.constant', foreground: '0070C1' },
  { token: 'metatag.html', foreground: '800000' },
  { token: 'type.identifier.css', foreground: '800000' },
  { token: 'attribute.name.css', foreground: 'FF0000' },
  { token: 'attribute.value.css', foreground: '0451A5' },
  { token: 'keyword.css', foreground: 'AF00DB' },
]

export function registerCodeEditMonacoThemes(monaco: MonacoApi): void {
  monaco.editor.defineTheme('code-edit-dark', {
    base: 'vs-dark',
    inherit: true,
    rules: darkPlusRules,
    encodedTokensColors: [],
    colors: {
      'editor.background': '#111418',
      'editor.foreground': '#D4D4D4',
      'editorLineNumber.foreground': '#4F5B67',
      'editorLineNumber.activeForeground': '#AEB8C5',
      'editorCursor.foreground': '#4FB3FF',
      'editor.selectionBackground': '#264F78',
      'editor.inactiveSelectionBackground': '#1C2B38',
      'editor.lineHighlightBackground': '#18202A',
      'editorIndentGuide.background1': '#26303A',
      'editorIndentGuide.activeBackground1': '#4F5B67',
      'editorGutter.background': '#111418',
      'editorBracketMatch.background': '#0E639C40',
      'editorBracketMatch.border': '#888888',
    },
  })

  monaco.editor.defineTheme('code-edit-light', {
    base: 'vs',
    inherit: true,
    rules: lightPlusRules,
    encodedTokensColors: [],
    colors: {
      'editor.background': '#F8FAFC',
      'editor.foreground': '#000000',
      'editorLineNumber.foreground': '#9AA8B5',
      'editorLineNumber.activeForeground': '#40505F',
      'editorCursor.foreground': '#006FBF',
      'editor.selectionBackground': '#ADD6FF',
      'editor.inactiveSelectionBackground': '#E1EDF7',
      'editor.lineHighlightBackground': '#EDF4FA',
      'editorIndentGuide.background1': '#D8E2EA',
      'editorIndentGuide.activeBackground1': '#AEBDCA',
      'editorGutter.background': '#F8FAFC',
      'editorBracketMatch.background': '#006FBF22',
      'editorBracketMatch.border': '#006FBF66',
    },
  })
}
